# Generated by Django 5.0.3 on 2024-04-11 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateField(default=datetime.datetime(2024, 4, 11, 11, 38, 25, 253769))),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
