# Generated by Django 5.0.3 on 2024-05-22 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateField(default=datetime.datetime(2024, 5, 22, 14, 15, 17, 983716))),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
