# Generated by Django 5.0.3 on 2024-05-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetails',
            name='info',
            field=models.TextField(),
        ),
    ]
