# Generated by Django 5.0.3 on 2024-05-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_appdetails_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetails',
            name='connection',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
