# Generated by Django 5.0.3 on 2024-04-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('joined_at', models.DateField()),
                ('passed_out', models.BooleanField(default=False)),
            ],
        ),
    ]
