# Generated by Django 5.0.3 on 2024-04-02 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('job', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 2, 13, 51, 22, 380759))),
            ],
        ),
    ]
