# Generated by Django 5.0.6 on 2024-06-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('pass_wd', models.CharField(max_length=100)),
                ('mail_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
