# Generated by Django 5.0.6 on 2024-06-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advancedMethods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginUsers',
            new_name='LoginCredUsers',
        ),
    ]
