# Generated by Django 5.0.6 on 2024-07-16 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancedMethods', '0005_bikemodel_premiumusers_bike_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_reason', models.IntegerField(choices=[(1, 'Service'), (2, 'brake down'), (3, 'puncture')])),
                ('block_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'rejected'), (2, 'accepted')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advancedMethods.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/uploads/')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advancedMethods.bike')),
            ],
        ),
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advancedMethods.bike')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advancedMethods.booking')),
            ],
        ),
    ]
