# Generated by Django 5.0.6 on 2024-08-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancedMethods', '0007_alter_images_image_trip_tripimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Completed'), (2, 'Upcoming'), (3, 'Cancelled')], default=0),
        ),
    ]
