# Generated by Django 5.0.6 on 2024-08-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advancedMethods', '0008_trip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripimages',
            name='path',
        ),
    ]
