# Generated by Django 5.0.6 on 2024-08-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancedMethods', '0011_userroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_1', models.CharField(max_length=100, unique=True)),
                ('col_2', models.CharField(max_length=100)),
                ('col_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestTable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_1', models.CharField(max_length=100, unique=True)),
                ('col_2', models.CharField(max_length=100)),
                ('test_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advancedMethods.testtable1')),
            ],
        ),
    ]
