# Generated by Django 5.0.3 on 2024-04-23 07:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=50)),
                ('created_at', models.DateField(default=datetime.date(2024, 4, 23))),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=50)),
                ('artist_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 23, 12, 53, 30, 620252))),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotifyApp.album')),
            ],
        ),
    ]
