# Generated by Django 5.0.3 on 2024-05-24 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 5, 24)),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 13, 48, 41, 200831)),
        ),
    ]
