# Generated by Django 5.0.3 on 2024-05-02 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyApp', '0003_alter_tracks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 14, 23, 58, 442822)),
        ),
    ]
