# Generated by Django 5.0.3 on 2024-05-03 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyApp', '0005_alter_album_created_at_alter_tracks_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 13, 36, 52, 751399)),
        ),
    ]
