# Generated by Django 5.0.3 on 2024-05-20 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyApp', '0007_alter_album_created_at_alter_tracks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 5, 20)),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 11, 51, 18, 693864)),
        ),
    ]
