# Generated by Django 5.0.6 on 2024-08-13 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyApp', '0009_alter_tracks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 12, 40, 25, 974424)),
        ),
    ]
