# Generated by Django 5.0.3 on 2024-05-22 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyApp', '0011_alter_album_created_at_alter_tracks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 5, 22)),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 12, 17, 48, 14994)),
        ),
    ]
